# Generated by Django 3.1.5 on 2023-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='egitmen_adi',
            field=models.CharField(default=2, help_text='Eğitmen Adını giriniz', max_length=200, unique=True, verbose_name='Eğitmen Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Kurs Açıklamasını Giriniz', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Kurs Adını Yazınız', max_length=200, unique=True, verbose_name='Kurs Adı'),
        ),
    ]
