# Generated by Django 3.1.5 on 2023-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230221_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='egitmen_adi',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
